=name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --junitxml=tests/test-results.xml  # Generate test results in XML format

      - name: Upload test results
        if: always()  # Ensure this step runs even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/test-results.xml
