name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --junitxml=tests/test-results.xml --maxfail=1 --disable-warnings -q > tests/test-results.txt

      - name: Upload XML test results for autograding
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-xml
          path: tests/test-results.xml

      - name: Upload plain text test results for humans
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-txt
          path: tests/test-results.txt
